/**
 * ASS 测试素材：优先用真实稿件，没有就就地合成。
 *
 * 为什么需要：有三个测试（export-roundtrip / parse-timeline / rows-timeline）
 * 早先硬编码 `projects/p-muz7axuw-f0bdc/subtitle.ass` —— 那是**本机测试数据**。
 * 清理项目后它们必然失败，而那不是代码坏了，是**假失败**：会掩盖真正的回归。
 * 仓库里不该有对某个本机稿件的依赖。
 *
 * 现在：
 *   · 有真实稿件 → 用它（保留原有的强验证：几十万行 Dialogue 的跨度/分布检查）
 *   · 没有       → makeSyntheticAss() 造一份结构完整的最小 ASS
 *
 * 断言因此统一成"相对输入自洽"的写法（跨度不变、解析链不压缩），
 * 而不是"必须 > 3000 秒"这种依赖具体素材的硬阈值。
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const REPO = path.resolve(HERE, '..');
export const JSMOD = path.join(HERE, 'jsmod');

/** 合成一份最小但结构完整的 ASS：中英双语 + 逐词 \c 高亮，跨度 238 秒 / 60 行 */
export function makeSyntheticAss() {
  const t = (s) => {
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    const sec = (s % 60).toFixed(2).padStart(5, '0');
    return `${h}:${String(m).padStart(2, '0')}:${sec}`;
  };
  const out = [
    '[Script Info]',
    '; Generated by tests/ass-fixture.mjs（合成素材，非本机数据）',
    'ScriptType: v4.00+',
    'PlayResX: 1920',
    'PlayResY: 1080',
    'WrapStyle: 3',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    'Style: Default,Microsoft YaHei,64,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,30,1',
    'Style: 中文字幕,Microsoft YaHei,72,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,2,2,2,10,10,60,1',
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
  ];
  for (let i = 0; i < 60; i++) {
    const a = i * 4, b = a + 3.8;
    out.push(`Dialogue: 0,${t(a)},${t(b)},中文字幕,,0,0,0,,第 ${i + 1} 句中文台词`);
    const words = ['This', 'is', `line${i + 1}`, 'of', 'synthetic', 'dialogue'];
    words.forEach((w, k) => {
      const s0 = a + (b - a) * (k / words.length);
      const s1 = a + (b - a) * ((k + 1) / words.length);
      const hl = words.slice(0, k).join(' ') + (k ? ' ' : '')
        + `{\\c&H00FF00&}${w}{\\c}` + ' ' + words.slice(k + 1).join(' ');
      out.push(`Dialogue: 0,${s0 === 0 ? '0:00:00.00' : t(s0)},${t(s1)},Default,,0,0,0,,${hl.trim()}`);
    });
  }
  return out.join('\n') + '\n';
}

/**
 * 找一份可用的 ASS：遍历 projects/*\/subtitle.ass，取第一个够大的。
 * 返回 { text, real, name }。
 */
export function resolveAssFixture() {
  const pdir = path.join(REPO, 'projects');
  try {
    for (const d of fs.readdirSync(pdir)) {
      const p = path.join(pdir, d, 'subtitle.ass');
      try {
        if (fs.statSync(p).size > 2000) {
          return { text: fs.readFileSync(p, 'utf8'), real: true, name: d };
        }
      } catch { /* 没有这个文件就继续找 */ }
    }
  } catch { /* projects 目录不存在 */ }
  return { text: makeSyntheticAss(), real: false, name: '(合成素材)' };
}

/** 从 ASS 文本里取出 Dialogue 的时间区间与条数（几个测试都要用） */
export function dialogueSpans(text) {
  const out = [];
  for (const line of String(text).split('\n')) {
    if (!line.startsWith('Dialogue:')) continue;
    const f = line.slice(9).split(',');
    const sec = (s) => {
      const m = /^(\d+):(\d+):([\d.]+)$/.exec(String(s || '').trim());
      return m ? (+m[1]) * 3600 + (+m[2]) * 60 + parseFloat(m[3]) : NaN;
    };
    const a = sec(f[1]), b = sec(f[2]);
    if (Number.isFinite(a) && Number.isFinite(b)) out.push([a, b]);
  }
  return out;
}

export function spanOf(spans) {
  if (!spans.length) return null;
  const lo = Math.min(...spans.map(s => s[0]));
  const hi = Math.max(...spans.map(s => s[1]));
  return { lo, hi, span: hi - lo, n: spans.length };
}
